### ISSUE TITLE
Welcome to nothing Discussions!

### ISSUE THREAD

**Issue by Aarohi0** [Mitraj-Ra/nothing#8]
### Discussed in https://github.com/Mitraj-Ra/nothing/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **Mitraj-Ra** February 14, 2023</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by Aarohi0** [comment]
this is a issue

**Comment by harshpalsinh05** [comment]
ok solved
